import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import '../../styles/globals.css';

const inter = Inter({
  variable: '--font-body',
  subsets: ['latin'],
  weight: ['400', '500'],
});

const poppins = Poppins({
  variable: '--font-head',
  subsets: ['latin'],
  weight: ['500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en' className={`${inter.variable} ${poppins.variable}`}>
      <body className='font-body bg-white dark:bg-black text-violet-dark dark:text-violet-light transition-colors'>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
